### ISSUE TITLE
The problem of pre-trained model

### ISSUE THREAD

**Issue by Mrfengchongren** [maulikres/HyperBox#1]
hello,the download link of the pre-trained model cannot be entered,I don't know what the problem is.   when I trained  the model myself,I could not reach the indicator you  gave on the music  dataset.I find the max_iterate is 1700,but It stopped after  1100  epochs, I don't  know  where  the  reason  is, can  you  answer  it?  Thank  you!

**Comment by maulikres** [comment]
Hi, I have added an alternative google drive link to download the pre-trained models.
https://drive.google.com/drive/folders/1wKgih_YJEbU04WJh5yXQhNmvBvEz7CYf?usp=sharing
